server:
  port: 8090
jwt:
  secret: secret
  expiration: 7200000 # 秒
  token: Authorization
spring:
  #  session:
  #    store-type: redis # session 的存储方式  session共享
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 个人服务器数据库
    url: 'jdbc:mysql://192.168.50.218/demo?useSSL=false'
    username: 'root'
    password: '123456'
  redis:
    database: 0
    host: 192.168.50.218
    port: 6379
    password: 123456
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.aegis.modules.*.model.*
#pagehelper
pagehelper:
  helperDialect: mysql # 方言
  reasonable: true # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: true # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: count=countSql
# 常量
wechat:
  corpid: ww4783b5de3fda6acd
  corpsecret: ww4783b5de3fda6acd